version: "3.8"

services:
  client:
    build:
      context: .
      dockerfile: docker/coolify/client.Dockerfile
    restart: always
    ports:
      - "80:3000"
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: docker/coolify/server.Dockerfile
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/checkmate
      - REDIS_URL=redis://redis:6379

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  mongo:
    image: mongo:6
    restart: always
    volumes:
      - ./mongo/data:/data/db
    ports:
      - "27017:27017"
